### ISSUE TITLE
スケジュール管理（予約状況、イベント俯瞰）の方法を決める

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.tsunashima#11]
サイトを持つ持たない以前の問題だが、開催予定のイベントや予約状況などが俯瞰できるようにAPIからJSON（か何か）でスケジュールのデータを受け取れるとなおよい。
少なくとも個人に依存する（矢萩の携帯とか）ような管理の仕方は避けたい。

**Comment by Kenta-Yahagi** [comment]
そうね。今後はそれぞれが好きなタイミングで使うから、そこは統一しておきたいね。
たとえばGoogle カレンダーとかでもいいんかな？

**Comment by kyoyababa** [comment]
@Kenta-Yahagi むしろGoogleカレンダーがいいと思うんだけど、予約システム的なものをもし持つなら、連携できんのかなあというのはわかんない。人力でGoogleカレンダーを埋めていくのが吝かでないのであれば、その限りではない。

**Comment by Kenta-Yahagi** [comment]
Google カレンダーは人力で埋めるで良いです！基本的に綱島の家は、オーナーとその界隈に半クローズド半オープンなスタンスで考えてるから。予約はオーナーがするてことで良いかな。

**Comment by kyoyababa** [comment]
DONE: Google Calendarと連携完了、OAuth認証済み、レイアウトは別途
