### ISSUE TITLE
okuruのコンセプト、考えてること

### ISSUE THREAD

**Issue by Kenta-Yahagi** [kyoyababa/okuru.tsunashima#13]
オーナーとなるそれぞれの人が、あまり矢萩の言ったことに合わせずに、それぞれの使い方をしてほしいと考えてたから、こっちで考えてることを書くます。

**Comment by Kenta-Yahagi** [comment]
実は裏で考えてることまとめた資料つくってるんだけど、それはハノイから帰ったらここに貼るます。

**Comment by Kenta-Yahagi** [comment]
まず自分のやりたいこと。

okuruで自分がやりたいことは、
オーナーの一人として、ワークショップだったり次の食いぶちを作る場所だったり、遊びに使ったりと考えてはいる。麻雀とか飲み会とかも含めてね。

ただ、全体的な目線ではリノベから家を運営していく過程でいかにそこのオーナー、家にきた人、参加した人が「思わずもう一度来たくなる、ハマる仕掛け」を作るっていう全体的なコミュニケーション、コミュニティデザインをしていきたいと思っている。

そのハマる仕掛けっていうのが、okuruっていう名前に込めた「恩を送る」て行為だと個人的に考えてる。人間て誰かにしてもらったことより、誰かに自分から何かした方が印象に残るっていうからね、いかに恩を思わず送りたくなる仕掛けをつくるか、それが俺のやってみたいこと、グランドデザイン。

そのグランドデザインにそれぞれのオーナーのもつコミュニティやイベントを自然な形で載せていきたいなーと考えてます。

**Comment by Kenta-Yahagi** [comment]
なので意識的に心掛けてるのは、コンセプトとかを自分から言わないこと。

オーナーによってやりたいことはそれぞれで、地域を巻き込んで行きたかったり、麻雀したかったり、野菜育てたかったり、ほんとそれぞれ。んで月に1万円それぞれが払うっていう制約を設けて、それが無駄にならないように使ってほしい。だからこそ自分からこういう方向で進めようと言った瞬間、従属的な空気間は作らないよー心掛けてる。

**Comment by Kenta-Yahagi** [comment]
okuruではポストシェアな空間にしたいなーと思ってて、すなはちある程度<オーナーの所有感>をだしたいなーと思ってる。
単純にシェアスペース、シェアハウス的発想であれば、それは誰しもがお金を払えば自由に来れて、開かれてる空間となるけど、正直そういうのは詰まる所お金儲けだし、それは個人でやればいいと思う。

まぁ自分の言葉でいえばシェアの先にあると思ってる新しい価値を実験してみたいと言ったところ。

あとね、複数人が無理のない範囲で２つ家を持つ機会ていうのは、実は無いよねと思ってる。そして同時に月一万という微妙に負担だなぁと思える金額、それすなはちオーナーは何かしらそこでやらないと無駄になるよね、と行動換気させる丁度いい金額設定かなーと。脱線。

**Comment by Kenta-Yahagi** [comment]
兎に角、考えてるのは
owned and openな空間。

所有感という居心地の良さがありつつ、その周辺の人には開かれてる空間というか。

具体的な設計として、スペースマーケットから流入する外様の人には、金額とかは意図的に高めの設定にして、Webサイトではokuruのコンセプトやストーリーを伝えてそれでも来てくれる人に貸す、で二回目以降はスペースマーケット介さずに借りれる(オーナーとつながる)的な設計。

あとはオーナー同士は家賃の回収や打ち合わせも兼ねて四半期に一回は家でミーティング、飲み会する。そこである程度、イベントの情報共有とかもする

**Comment by kyoyababa** [comment]
NOTE: 矢萩がここに書いたことを別途整理して分類する

**Comment by kyoyababa** [comment]
thanks, close.
