### ISSUE TITLE
ドメインとサーバーの検討と決定

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.tsunashima#5]
* 有料ドメインか、無料ドメインか
* レンタルサーバーをどうするか。もはや自分たちで立てるか。
=> いずれにしろ責任の所在と保守性を最優先したい

**Comment by Kenta-Yahagi** [comment]
サーバーはまゆげ持ってたな、heroku。
リノベをやる前の前身の活動でまゆげにもろもろ作ってもらってたので。

あとインフラ周りはまゆげやりたいって話してたし、お願いしようと思う。

**Comment by kyoyababa** [comment]
@Kenta-Yahagi そしたら、まゆげさんとのコミュニケーションは任せます。本名よくわかんないし、何をしてもらう必要があるのかもよくわからん。

**Comment by kyoyababa** [comment]
NOTE: なんか誰かがサーバーでnpm deployできるようにしていてくれたきがする

**Comment by Kenta-Yahagi** [comment]
サーバはとりあえず、まゆげが建ててくれてデプロイまでできるよーになってます。ドメインは取得せんとね。まゆげにお願いしておくわ。

**Comment by kyoyababa** [comment]
@Kenta-Yahagi そしたら、ドメインに紐付いてメールアドレスが取得できるようになると思うから、メールアドレスが使えるようになったらいろんな各種サービスのアカウント取得とかを一気に進めちゃおう。

**Comment by Kenta-Yahagi** [comment]
メールアドレス使えるようになったらifttt使ってslackか何かにメールがきたこと通知するようにしたいなー。

**Comment by kyoyababa** [comment]
NOTE: okuru.yokohama	でよさそう、サーバーもついてくるので問題なし。

**Comment by kyoyababa** [comment]
DONE: http://okuru.yokohama
